# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pipilene-correta

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_acf5ef9177c34122bb07edd6c12c6db7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a1293c93fea64dd589f0d4aa51972010 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_acf5ef9177c34122bb07edd6c12c6db7 }}/pipeline-correta:${{ github.sha }}
        file: ./Dockerfile

  test:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    
    - name: npm install, and test
      run:
        npm install
        npm run test --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pipilene-correta'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ef0e457ec02344629c771098835925e4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_acf5ef9177c34122bb07edd6c12c6db7 }}/pipeline-correta:${{ github.sha }}'